### ISSUE TITLE
TimeCrowd連携

### ISSUE THREAD

**Issue by pandeiro245** [pandeiro245/freee2kintone#9]
- [ ] TimeEntryのデータを保存
- [ ] Taskのデータを保存

**Comment by pandeiro245** [comment]
Rubyのバージョンが2.1.3だったので2.2.0にする

**Comment by pandeiro245** [comment]
![image](https://cloud.githubusercontent.com/assets/125965/12009609/1968f612-acc3-11e5-8d2e-eb0d96570762.png)
バージョン上げてもかわらず

**Comment by pandeiro245** [comment]
現在：
![image](https://cloud.githubusercontent.com/assets/125965/12015579/b2ce9a0a-ad81-11e5-827b-a5cf2fb76be8.png)

うまくいっている環境（hareruya）：
![image](https://cloud.githubusercontent.com/assets/125965/12015586/ddc27a92-ad81-11e5-9c8e-244cdb1ff9d6.png)

**Comment by tnantoka** [comment]
omniauthを1.1.1に落として見たけどダメ。

**Comment by tnantoka** [comment]
```
gem 'omniauth-oauth2', '1.3.1'
```

```
$ bundle update omniauth-oauth2
```

で解消。

**Comment by pandeiro245** [comment]
https://github.com/pandeiro245/kintone_sync/issues/5
